name: publish_debian_package
on:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosdistro: [foxy, galactic]
        package:
          - [OUXT-Polaris, ouxt_common]
    container: wamvtan/debian_package_builder:${{ matrix.rosdistro }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ouxt_distro
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.package[0] }}/${{ matrix.package[1] }}
          path: ${{ matrix.package[1] }}
      - name: update rosdep list
        run: echo yaml file://$GITHUB_WORKSPACE/ouxt_distro/rosdep.yaml >> /etc/ros/rosdep/sources.list.d/10-local.list
      - name: rosdep update and apt update
        run: rosdep update && apt update
      - name: install depends
        run: rosdep install -iry --from-paths ${{ matrix.package[1] }} --ignore-src --rosdistro=${{ matrix.rosdistro }}
      - name: bloom generate
        run: colcon list -t -p | xargs -L 1 bash -c 'cd "$0" && bloom-generate rosdebian --ros-distro ${{ matrix.rosdistro }}'
      - name: generate debian package
        run: colcon list -t -p | xargs -L 1 bash -c 'cd "$0" && fakeroot debian/rules binary'
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ${{ matrix.package[1] }}/*.deb
  get_package_list:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - uses: jitterbit/get-changed-files@v1
        id: get_debian_packages
        with:
          format: 'json'
  publish_apt_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - []
    needs: get_package_list
    steps:
      - uses: jrandiny/apt-repo-action@master
        with:
          github_token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          repo_supported_arch: |
            amd64
          repo_supported_version: |
            focal
          file: ${{ steps.get_debian_package_lists.outputs.packages }}
          file_target_version: focal
          public_key: ${{ secrets.OUXT_APT_REPO_PUBLIC_KEY }}
          private_key: ${{ secrets.OUXT_APT_REPO_PASSPHRASE }}
          key_passphrase: ${{ secrets.OUXT_APT_REPO_PASSPHRASE }}