name: yamllint
on:
  schedule:
  - cron: 0 0 * * *
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: rosdep.yaml
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
